/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package empmgmt.gui;

import empmgmt.dao.EmployeeDAO;
import empmgmt.pojo.Employee;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Abhishek Live
 */
public class ViewAllEmployeeFrame extends javax.swing.JFrame {

    /**
     * Creates new form ViewAllEmployeeDetails
     */
    public ViewAllEmployeeFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ViewAllEmployeeDetails = new javax.swing.JPanel();
        lblTITLE = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtAreaResult = new javax.swing.JTextArea();
        btnResult = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ViewAllEmployeeDetails.setBackground(new java.awt.Color(0, 0, 0));
        ViewAllEmployeeDetails.setForeground(new java.awt.Color(255, 255, 255));

        lblTITLE.setBackground(new java.awt.Color(0, 0, 0));
        lblTITLE.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblTITLE.setForeground(new java.awt.Color(255, 255, 255));
        lblTITLE.setText("View All Employee Details ");

        TxtAreaResult.setColumns(20);
        TxtAreaResult.setRows(5);
        jScrollPane1.setViewportView(TxtAreaResult);

        btnResult.setBackground(new java.awt.Color(0, 0, 0));
        btnResult.setForeground(new java.awt.Color(255, 255, 255));
        btnResult.setText("Show All Recordes ");
        btnResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ViewAllEmployeeDetailsLayout = new javax.swing.GroupLayout(ViewAllEmployeeDetails);
        ViewAllEmployeeDetails.setLayout(ViewAllEmployeeDetailsLayout);
        ViewAllEmployeeDetailsLayout.setHorizontalGroup(
            ViewAllEmployeeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewAllEmployeeDetailsLayout.createSequentialGroup()
                .addGroup(ViewAllEmployeeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewAllEmployeeDetailsLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(btnResult)
                        .addGap(41, 41, 41)
                        .addComponent(btnBack))
                    .addGroup(ViewAllEmployeeDetailsLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewAllEmployeeDetailsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTITLE, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );
        ViewAllEmployeeDetailsLayout.setVerticalGroup(
            ViewAllEmployeeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewAllEmployeeDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTITLE, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addGap(31, 31, 31)
                .addGroup(ViewAllEmployeeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnResult)
                    .addComponent(btnBack))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ViewAllEmployeeDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ViewAllEmployeeDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultActionPerformed
       try{
           ArrayList<Employee> empList =EmployeeDAO.getAllEmployee();
            if(empList.size()==0)
            {
                JOptionPane.showMessageDialog(null,"NO RECORD PRESENT IN THE DATABASE","NO RECORD FOUND !", JOptionPane.ERROR_MESSAGE);
                return;
            }
            StringBuffer sb =new StringBuffer();
            sb.append("EMPID\tEMPNAME\tEMPSAL\n\n");
            for(Employee e :empList){
                sb.append(e.getEmpId()+"\t"+e.getEmpName()+"\t"+e.getEmpSal()+"\n");
            }
            TxtAreaResult.setText(sb.toString());
            }
            catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"DataBase Error", "DB Error !" ,JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnResultActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        OptionsFrameUI mainFrame =new OptionsFrameUI();
        mainFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAllEmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAllEmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAllEmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAllEmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAllEmployeeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TxtAreaResult;
    private javax.swing.JPanel ViewAllEmployeeDetails;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnResult;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTITLE;
    // End of variables declaration//GEN-END:variables
}
